version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:                                                                           
      - 8000:8000   
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    environment:
        MYSQL_DATABASE: adminapp
        MYSQL_USER: root
        MYSQL_PASSWORD: Admin
        MYSQL_ROOT_PASSWORD: Admin
    volumes:
      - .dbdatabase:/var/lib/mysql
    ports:
    - 33068:3306
